# Generated by Django 3.2 on 2021-04-29 14:55

from django.db import migrations


def create_data(apps, schema_editor):
    User = apps.get_model('user', 'User')
    User(first_name="User 001", last_name="User 001", email="user001@email.com", phone="00000000",
         address="User 000 Address", description="User 001 description").save()


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
